### ISSUE TITLE
Online function

### ISSUE THREAD

**Issue by Jasperschiks** [andrey-leshenko/WaTracker#4]
Online function doesn't work.

Are you still working on this application?

**Comment by andrey-leshenko** [comment]
Hello Jasperschiks,

The 'Online' window stopped working for me too.
Sadly, Google [announced](https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html) that they will stop supporting Chrome Apps (which is what this app is) from early 2018, so the app will stop working in a few months anyway.

The next step is to rewrite the app into a Chrome Extension, or maybe something else.
I may do this sometime, but it probably won't be soon.

Thanks for your interest,
Andrey

**Comment by andrey-leshenko** [comment]
Update: I went and fixed it anyway.

I'll be happy to hear whether that solved the problem for you.

-Andrey

**Comment by Jasperschiks** [comment]
That's nice to hear, I'll check it out soon. Too bad Google is not supporting apps in the future. I'll look into the code and try to make an extension out of it. If I have the time. Will probably be some work

**Comment by chelorossi** [comment]
It is working!,
thanks for the awesome work.

-cheluskis
